# Generated by Django 4.1.7 on 2023-02-16 06:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_am', models.CharField(choices=[('reseller', 'reseller'), ('residential customer', 'residential'), ('commercial customer', 'commercial customer')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address_ln1', models.CharField(max_length=100)),
                ('address_ln2', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(max_length=50)),
                ('comment', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
    ]
