# Generated by Django 4.1.7 on 2023-02-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='i_am',
            field=models.CharField(choices=[('reseller', 'reseller'), ('commercial customer', 'commercial customer'), ('residential customer', 'residential')], max_length=30),
        ),
    ]
