# Generated by Django 4.1.7 on 2023-02-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_products_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='image_gallery/')),
            ],
        ),
        migrations.AlterField(
            model_name='reserve',
            name='i_am',
            field=models.CharField(choices=[('Residentail Customer', 'Residentail Customer'), ('Reseller', 'Reseller'), ('Commercial Customer', 'Commercial Customer')], max_length=30),
        ),
    ]
