# Generated by Django 4.1.7 on 2023-02-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_image_gallery_alter_reserve_i_am'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_gallery',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='i_am',
            field=models.CharField(choices=[('Reseller', 'Reseller'), ('Commercial Customer', 'Commercial Customer'), ('Residentail Customer', 'Residentail Customer')], max_length=30),
        ),
    ]
