# Generated by Django 4.1.7 on 2023-02-17 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_reserve_i_am'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='projects/')),
                ('desc', models.CharField(default='We are updating information regarding this project soon', max_length=2000)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reserve',
            name='i_am',
            field=models.CharField(choices=[('Commercial Customer', 'Commercial Customer'), ('Reseller', 'Reseller'), ('Residentail Customer', 'Residentail Customer')], max_length=30),
        ),
        migrations.CreateModel(
            name='products_usedin_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.products')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projects')),
            ],
        ),
    ]
