# Generated by Django 4.1.7 on 2023-02-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_projects_alter_reserve_i_am_products_usedin_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='year_of_project',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='i_am',
            field=models.CharField(choices=[('Reseller', 'Reseller'), ('Residentail Customer', 'Residentail Customer'), ('Commercial Customer', 'Commercial Customer')], max_length=30),
        ),
    ]
