# Generated by Django 4.1.7 on 2023-02-19 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_reserve_i_am_alter_team_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='i_am',
            field=models.CharField(choices=[('Commercial Customer', 'Commercial Customer'), ('Reseller', 'Reseller'), ('Residentail Customer', 'Residentail Customer')], max_length=30),
        ),
        migrations.CreateModel(
            name='varient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varient_name', models.CharField(max_length=100, unique=True)),
                ('desc', models.FileField(upload_to='varients/')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.products')),
            ],
        ),
    ]
