# Generated by Django 4.1.7 on 2023-02-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_whats_new_pinned_alter_projects_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='i_am',
            field=models.CharField(choices=[('Reseller', 'Reseller'), ('Commercial Customer', 'Commercial Customer'), ('Residentail Customer', 'Residentail Customer')], max_length=30),
        ),
    ]
