# Generated by Django 4.1.7 on 2023-02-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_whats_new_top_alter_reserve_i_am'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_gallery',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='i_am',
            field=models.CharField(choices=[('Commercial Customer', 'Commercial Customer'), ('Residentail Customer', 'Residentail Customer'), ('Reseller', 'Reseller')], max_length=30),
        ),
        migrations.AlterField(
            model_name='whats_new',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
