# Generated by Django 4.1.7 on 2023-03-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_projects_space_saved_projects_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='i_am',
            field=models.CharField(choices=[('Residentail Customer', 'Residentail Customer'), ('Commercial Customer', 'Commercial Customer'), ('Reseller', 'Reseller')], max_length=30),
        ),
    ]
