# Generated by Django 4.1.7 on 2023-02-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_reserve_i_am'),
    ]

    operations = [
        migrations.CreateModel(
            name='why_powertree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_problem', models.CharField(max_length=100)),
                ('traditional_approach', models.CharField(max_length=100)),
                ('powertree_approach', models.CharField(max_length=100)),
                ('traditional_image', models.ImageField(upload_to='why_powertree/')),
                ('powertree_image', models.ImageField(upload_to='why_powertree/')),
            ],
        ),
        migrations.AlterField(
            model_name='reserve',
            name='i_am',
            field=models.CharField(choices=[('Reseller', 'Reseller'), ('Commercial Customer', 'Commercial Customer'), ('Residentail Customer', 'Residentail Customer')], max_length=30),
        ),
    ]
