# Generated by Django 4.1.7 on 2023-02-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='desc',
            field=models.CharField(default='product descriptions', max_length=2000),
        ),
    ]
