# Generated by Django 4.1.7 on 2023-02-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_products_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sub_text',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='i_am',
            field=models.CharField(choices=[('Commercial Customer', 'Commercial Customer'), ('Residentail Customer', 'Residentail Customer'), ('Reseller', 'Reseller')], max_length=30),
        ),
    ]
