# Generated by Django 4.1.7 on 2023-02-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_whats_new_alter_reserve_i_am'),
    ]

    operations = [
        migrations.AddField(
            model_name='whats_new',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='desc',
            field=models.TextField(default='We are updating information regarding this project soon', max_length=2000),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='i_am',
            field=models.CharField(choices=[('Reseller', 'Reseller'), ('Residentail Customer', 'Residentail Customer'), ('Commercial Customer', 'Commercial Customer')], max_length=30),
        ),
    ]
