# Generated by Django 4.1.7 on 2023-02-23 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_pinned_remove_whats_new_pinned_alter_reserve_i_am'),
    ]

    operations = [
        migrations.AddField(
            model_name='whats_new',
            name='top',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pinned'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='i_am',
            field=models.CharField(choices=[('Reseller', 'Reseller'), ('Commercial Customer', 'Commercial Customer'), ('Residentail Customer', 'Residentail Customer')], max_length=30),
        ),
    ]
