# Generated by Django 4.1.7 on 2023-02-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_image_gallery_desc_alter_reserve_i_am_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varient',
            name='varient_name',
            field=models.CharField(max_length=100),
        ),
    ]
