# Generated by Django 4.1.7 on 2023-03-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_reserve_i_am'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisory_board',
            name='image',
            field=models.ImageField(upload_to='advisory/'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='i_am',
            field=models.CharField(choices=[('Commercial Customer', 'Commercial Customer'), ('Residentail Customer', 'Residentail Customer'), ('Reseller', 'Reseller')], max_length=30),
        ),
    ]
