# Generated by Django 4.1.7 on 2023-04-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator_query',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
